AWSTemplateFormatVersion: 2010-09-09
Description: Create a role to authorize the VPC Peering request from a specific account, this is used to create the VPC Peer between different accounts in CloudFormation
 
Parameters: 
  RequestedAccountNumber:
    Type:
    Default:
    Description:
    AllowedPattern:
    ConstraintDescription:

Resources:
  VPCPeeringAuthorizerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              Fn::Join:
              - ''
              - - 'arn:aws:iam::'
                - Ref: RequesterAccountNumber
                - ":root"
          Action: sts:AssumeRole
      Policies:
      - PolicyName: VPCAuthorizer
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - ec2:AcceptVpcPeeringConnection
            Resource:
            - "*"
Outputs:
  RoleName:
    Description: Cross Account Role Name
    Value:
      Ref: VPCPeeringAuthorizationRole
